using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Soenneker.Bland.Calls.Responses;

public class CallDetailsResponse
{
    /// <summary>
    /// The unique identifier for the call.
    /// </summary>
    [JsonPropertyName("call_id")]
    public string? CallId { get; set; }

    /// <summary>
    /// The length of the call in minutes.
    /// </summary>
    [JsonPropertyName("call_length")]
    public float? CallLength { get; set; }

    /// <summary>
    /// The batch ID if the call is part of a batch.
    /// </summary>
    [JsonPropertyName("batch_id")]
    public string? BatchId { get; set; }

    /// <summary>
    /// The phone number that received the call.
    /// </summary>
    [JsonPropertyName("to")]
    public string? To { get; set; }

    /// <summary>
    /// The phone number that made the call.
    /// </summary>
    [JsonPropertyName("from")]
    public string? From { get; set; }

    /// <summary>
    /// Details about parameters in the original API request.
    /// </summary>
    [JsonPropertyName("request_data")]
    public RequestData? RequestData { get; set; }

    /// <summary>
    /// Whether the call has been completed.
    /// </summary>
    [JsonPropertyName("completed")]
    public bool? Completed { get; set; }

    /// <summary>
    /// The timestamp for when the call request was created.
    /// </summary>
    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }

    /// <summary>
    /// Whether the call was inbound or outbound.
    /// </summary>
    [JsonPropertyName("inbound")]
    public bool? Inbound { get; set; }

    /// <summary>
    /// The status of the call.
    /// </summary>
    [JsonPropertyName("queue_status")]
    public string? QueueStatus { get; set; }

    /// <summary>
    /// The URL of the deployment that handled the call.
    /// </summary>
    [JsonPropertyName("endpoint_url")]
    public string? EndpointUrl { get; set; }

    /// <summary>
    /// The maximum allowed duration of the call in minutes.
    /// </summary>
    [JsonPropertyName("max_duration")]
    public float? MaxDuration { get; set; }

    /// <summary>
    /// Any error message encountered during the call, if applicable.
    /// </summary>
    [JsonPropertyName("error_message")]
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// Variables created during the call, including system variables.
    /// </summary>
    [JsonPropertyName("variables")]
    public BlandCallVariables? Variables { get; set; }

    /// <summary>
    /// Who answered the call (e.g., human, voicemail, etc.).
    /// </summary>
    [JsonPropertyName("answered_by")]
    public string? AnsweredBy { get; set; }

    /// <summary>
    /// Indicates whether the call was recorded.
    /// </summary>
    [JsonPropertyName("record")]
    public bool? Record { get; set; }

    /// <summary>
    /// The URL of the call recording if available.
    /// </summary>
    [JsonPropertyName("recording_url")]
    public string? RecordingUrl { get; set; }

    /// <summary>
    /// Metadata associated with the call.
    /// </summary>
    [JsonPropertyName("metadata")]
    public object? Metadata { get; set; }

    /// <summary>
    /// A short summary of the call based on the transcript.
    /// </summary>
    [JsonPropertyName("summary")]
    public string? Summary { get; set; }

    /// <summary>
    /// The cost of the call in USD.
    /// </summary>
    [JsonPropertyName("price")]
    public float? Price { get; set; }

    /// <summary>
    /// The time the call was connected.
    /// </summary>
    [JsonPropertyName("started_at")]
    public string? StartedAt { get; set; }

    /// <summary>
    /// Whether Local Dialing was enabled for the account during the call.
    /// </summary>
    [JsonPropertyName("local_dialing")]
    public bool? LocalDialing { get; set; }

    /// <summary>
    /// Who ended the call (e.g., ASSISTANT or USER).
    /// </summary>
    [JsonPropertyName("call_ended_by")]
    public string? CallEndedBy { get; set; }

    /// <summary>
    /// Pathway logs for calls that have detailed information about nodes and internal reasoning.
    /// </summary>
    [JsonPropertyName("pathway_logs")]
    public string? PathwayLogs { get; set; }

    /// <summary>
    /// The structure used for post-call analysis.
    /// </summary>
    [JsonPropertyName("analysis_schema")]
    public object? AnalysisSchema { get; set; }

    /// <summary>
    /// Data generated by post-call analysis.
    /// </summary>
    [JsonPropertyName("analysis")]
    public object? Analysis { get; set; }

    /// <summary>
    /// A single string containing all of the text from the call excluding system messages.
    /// </summary>
    [JsonPropertyName("concatenated_transcript")]
    public string? ConcatenatedTranscript { get; set; }

    /// <summary>
    /// The array of transcripts (phrases) spoken during the call.
    /// </summary>
    [JsonPropertyName("transcripts")]
    public List<BlandCallTranscript>? Transcripts { get; set; }

    /// <summary>
    /// The status of the call.
    /// </summary>
    [JsonPropertyName("status")]
    public string? Status { get; set; }

    /// <summary>
    /// The corrected duration of the call in seconds.
    /// </summary>
    [JsonPropertyName("corrected_duration")]
    public string? CorrectedDuration { get; set; }

    /// <summary>
    /// The time the call ended.
    /// </summary>
    [JsonPropertyName("end_at")]
    public string? EndAt { get; set; }
}